### ISSUE TITLE
Not working in Android

### ISSUE THREAD

**Issue by favistech** [TheSmiths-Widgets/ts.chat#3]
Hi,

I'm getting the following error when trying to use Ti.Chat (and ts.messageBuilderFactory - messenger_like) with Android. Any ideas?

[ERROR] :  TiApplication: (main) [152,1174676] Sending event: exception on thread: main msg:java.lang.ClassCastException: java.util.HashMap cannot be cast to org.appcelerator.titanium.proxy.TiViewProxy; Titanium 4.1.0,2015/07/06 11:15,d57aa7d
[ERROR] :  TiApplication: java.lang.ClassCastException: java.util.HashMap cannot be cast to org.appcelerator.titanium.proxy.TiViewProxy
[ERROR] :  TiApplication:   at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:231)
[ERROR] :  TiApplication:   at org.appcelerator.titanium.proxy.TiWindowProxy.handleMessage(TiWindowProxy.java:102)
[ERROR] :  TiApplication:   at ti.modules.titanium.ui.WindowProxy.handleMessage(WindowProxy.java:428)
[ERROR] :  TiApplication:   at android.os.Handler.dispatchMessage(Handler.java:106)
[ERROR] :  TiApplication:   at android.os.Looper.loop(Looper.java:193)
[ERROR] :  TiApplication:   at android.app.ActivityThread.main(ActivityThread.java:5299)
[ERROR] :  TiApplication:   at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] :  TiApplication:   at java.lang.reflect.Method.invoke(Method.java:515)
[ERROR] :  TiApplication:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
[ERROR] :  TiApplication:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
[ERROR] :  TiApplication:   at dalvik.system.NativeStart.main(Native Method)

Thanks

**Comment by KtorZ** [comment]
Hey!
Can you provide a snippet of the code causing that error ?

**Comment by favistech** [comment]
Hey, thanks for the prompt reply.

``` javascript
$.winMessaging.addEventListener('open', function (e) {
    $.vwMessages = Alloy.createWidget('ts.chat');
    $.vwMessages.init({
        messageBuilder: Alloy.createWidget('ts.messageBuilderFactory').getBuilder("messenger_like", {
            user: sender
        })
    });
    $.vwMessages.on('load', function (loadEvent) {
    });
    $.vwMessages.on('newmessage', function (newMessageEvent) {
    });
    $.winMessaging.add($.vwMessages);
});  
```

```
<Alloy>
    <Window id="winMessaging" class='container' navBarHidden="true" layout="vertical">
    </Window>
</Alloy>
```

**Comment by KtorZ** [comment]
You can't add a widget instance to a window / view. A widget instance is nothing more than a controller instance. So, try to do this instead :

```
$.winMessaging.add($.vwMessages.getView());
```

**Comment by favistech** [comment]
Thank you, that did it and got past that exception! I am getting the following now though:

[ERROR] :  TiExceptionHandler: (main) [42,24040] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [2,24042] - In alloy/widgets/ts.chat/controllers/widget.js:1,69
[ERROR] :  TiExceptionHandler: (main) [1,24043] - Message: Uncaught TypeError: Cannot read property 'rect' of undefined
[ERROR] :  TiExceptionHandler: (main) [1,24044] - Source: emoveEventListener("postlayout",e),d.messagesWrapper.height=d.parent.rect.heig
[ERROR] :  V8Exception: Exception occurred at alloy/widgets/ts.chat/controllers/widget.js:1: Uncaught TypeError: Cannot read property 'rect' of undefined

**Comment by KtorZ** [comment]
Well ... I didn't test about adding the widget dynamically to a view / window :/ 
Could you add this before adding the widget to the window :

```
$.vwMessages.parent = $.winMessaging;
```

and tell me if it solves your problem.

**Comment by favistech** [comment]
That solved the issue, thank you for your help!
