### ISSUE TITLE
better documentation

### ISSUE THREAD

**Issue by albert0m** [TheSmiths-Widgets/ts.chat#4]
Hi,
I just downloaded the widget and it's superb, but I'm struggling in making it work.
Is it possible to have a complete app.js to look at?

I just would like an example on how to include the widget, send and receive messages.

Thank you!

**Comment by KtorZ** [comment]
Hey!
Have a look at the `test` branch:

https://github.com/TheSmiths-Widgets/ts.chat/tree/test/app

**Comment by albert0m** [comment]
this is exactly what I was looking for! thank you!

**Comment by thecubeweb** [comment]
When I execute the test app, it shows:

Script Error Couldn't find module: alloy/widgets/ts.chat/controllers/widget for architecture: x86_64

Any clues?

**Comment by KtorZ** [comment]
Could you describe your environnement a bit ? 
Which Ti version, which Alloy version, windows, mac or linux ?

Thanks.

**Comment by thecubeweb** [comment]
I'm testing on a mac with Ti 3.5.0 and Alloy 1.7.6.

**Comment by KtorZ** [comment]
I've just clone the repo and tried to compile for iOS with Ti 3.5.1.GA on a mac with Alloy 1.6.2; it's working fine. 
I hardly think that there is a significant difference between 3.5.1.GA and 3.5.0; same for Alloy. 
Are you trying to compile to Android ?

**Comment by thecubeweb** [comment]
On Android it shows that error:
Uncaught Error: Requested module not found: alloy/widgets/ts.chat/controllers/widget

**Comment by KtorZ** [comment]
I don't know... It sounds like some files are missing in your working tree. 
Try to clean before compiling again, and maybe, try to delete the test branch, clean your working tree and checkout again using the remote version.

**Comment by KtorZ** [comment]
Did you double-check if you correctly added the widget to your `config.json` file ?
